Models/NhmSong.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace NhmLesson06.Models
{
    public class NhmSong
    {
        [Key]
        public int Id { get; set; }
        [Required(ErrorMessage = "Nhm: Hãy nhâp ứng viên")]
        [DisplayName("Tieu De")]
        public string NhmTitle { get; set; }
        [Required(ErrorMessage = "Nhm: Hay Nhap nhan vien")]
        [DisplayName("NV chinh")]
        public string NhmAuthor { get; set; }
        [Required(ErrorMessage = "Nhm: Hay Nhap ten")]
        [StringLength (50,MinimumLength =2,ErrorMessage ="Ten co toi thieu 2 ky tu,toi da 50 ky tu")]
        public string NhmArtist { get; set; }
        [Required(ErrorMessage = "Nhm: Hay Nhap Nguoi Dung")]
        [RegularExpression(@"[0-9][4]",ErrorMessage ="Nhm:Nhap xuat phai co 2 ky tu so")]
        [Range(1900,2004,ErrorMessage ="Nhm:Nam sinh trong khoang tu 1900-2004")]
        [DisplayName("Nam Sinh")]
        public int NhmYearRelease { get; set; }

    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NhmLesson06.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Controllers/NhmSongController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using NhmLesson06.Models;
using System.ComponentModel.DataAnnotations;

namespace NhmLesson06.Controllers
{
    public class NhmSongController : Controller
    {
        private static List<NhmSong> nhmSongs = new List<NhmSong>()
        {
            new NhmSong{Id=22109044,NhmTitle="NgoHoangMinh", NhmArtist="CNTT",NhmAuthor="NTU", NhmYearRelease=2023},
            new NhmSong{Id=1,NhmTitle="NgoHoangMinh", NhmArtist="K22CNTT",NhmAuthor="NTU", NhmYearRelease=2020}
        };
    
        
        // GET: NhmSong
        public ActionResult NhmIndex()
        {
            return View(nhmSongs);
        }
        public ActionResult NhmCreate()
        {
            var nhmSong = new NhmSong();
            return View(nhmSong);
        }
    }
}

Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

Views/NhmSong/NhmCreate.cshtml
@model NhmLesson06.Models.NhmSong

@{
    ViewBag.Title = "NhmCreate: Thêm mới ứng viên ";
}

<h2>NhmCreate: +1 Ứng Viên</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>NhmSong</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.NhmTitle, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NhmTitle, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NhmTitle, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NhmAuthor, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NhmAuthor, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NhmAuthor, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NhmArtist, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NhmArtist, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NhmArtist, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NhmYearRelease, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NhmYearRelease, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NhmYearRelease, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" name="btnNhm" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/NhmSong/NhmIndex.cshtml
@model IEnumerable<NhmLesson06.Models.NhmSong>

@{
    ViewBag.Title = "Nhm:Danh sách ứng viên";
}

<h2>Nhm Danh sách ứng vieen</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.NhmTitle)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NhmAuthor)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NhmArtist)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NhmYearRelease)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.NhmTitle)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NhmAuthor)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NhmArtist)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NhmYearRelease)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Ngô Hoàng Minh", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })</li>
                    <li>@Html.ActionLink("About", "About", "Home", new { area = "" }, new { @class = "navbar-brand" })</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home", new { area = "" }, new { @class = "navbar-brand" })</li>
                    <li>@Html.ActionLink("NHM : Danh sách ứng viên", "NhmIndex", "NhmSong", new { area = "" }, new { @class = "navbar-brand" })</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>